### ISSUE TITLE
Match query /match/{id} is only accessible  by internal id

### ISSUE THREAD

**Issue by hoersamu** [HeLO-System/HeLO-Server#37]
The /match/{id} is only accessible by passing the uuid (6264815d5970d05c05087878) not the match id (CoRe-WTH-2021-11-21).
This is problematic since score objects only have the match_id not the match_uuid as reference

**Comment by Soxxes** [comment]
fixed, performs a full text search now for a match_id, e.g. CoRe-WTH-2021-11-21
however, if one only provides an incomplete match_id this will raise an AttributeError and returns the following error msg:
"multiple errors: You did not provide a valid object id, instead I looked for a match with the match_id '{oid}', but couldn't find any.", error code 400

**Comment by hoersamu** [comment]
Lgtm 👍
